response_type: dict[str, str] = {"2": "lineal", "3": "quadratic", "4": "cubic"}

property_multiplicities: dict[str, int] = {
    "one": 3,
    "overlap": 1,
    "nucpot": 1,
    "kinetic": 1,
    "angmom": 1,
    "sd": 3,
    "sdke": 3,
    "psdke": 3,
    "fc": 3,
    "fcke": 3,
    "pfcke": 3,
    "darwin": 1,
    "massvelo": 1,
    "nelfld": 1,
    "diplen": 1,
    "dipvel": 1,
    "pso": 1,
    "nstcgo": 1,
    "dnske": 1,
    "psoke": 1,
    "psomv": 1,
    "psooz": 1,
    "ozso": 3,
    "ozke": 1,
    "ozmv": 1,
    "szke": 3,
    "szmv": 3,
    # othres
    "psolap": 1,
    "cdnske": 1,
    # & didj
    "dxdx": 3,
    "dydy": 3,
    "dzdz": 3,
    # & laplacian didj
    # &
    "sofiel": 3,
    "spinorbit": 3,
    "pnstcgop": 1,
    "pangmomp": 1,
    "ppsop": 1,
    "curllgxp": 3,
    "curllgyp": 3,
    "curllgzp": 3,
    "pxabx": 3,
    "pxaby": 3,
    "pxabz": 3,
    "lap_abxxp": 3,
    "lap_abyxp": 3,
    "lap_abzxp": 3,
    "lap_pxabx": 3,
    "lap_pxaby": 3,
    "lap_pxabz": 3,
    "lapauxxp": 3,
    "rpsod": 1,
}
