response_type: dict[str, str] = {"2": "lineal", "3": "quadratic", "4": "cubic"}

property_multiplicities: dict[str, int] = {
    "overlap": 1,
    "nucpot": 1,
    "kinetic": 1,
    "angmom": 1,
    "sd": 3,
    "fc": 3,
    "darwin": 1,
    "massvelo": 1,
    "nelfld": 1,
    "diplen": 1,
    "dipvel": 1,
    "pso": 1,
    "nstcgo": 1,
    "dnske": 1,
    "psoke": 1,
    "psooz": 1,
    "ozke": 1,
    "laplacian": 1,
    "sofiel": 3,
    "spinorbit": 3,
    "pnstcgop": 1,
    "pangmomp": 1,
}
