# ref: https://github.com/marketplace/actions/pytest-coverage-commentator
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Code Testing and Coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    # Work on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Download Repository)
        uses: actions/checkout@v3 # checkout the repository content to github runner
      # Install python
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          pwd
          ls
          python -m pip install --upgrade pip
          pip install flake8 
          pip install -r requirements.txt
          cd src/hermite
          f2py3 -c -m f90recursives recursives.F90 --f90flags="-m64 -cpp -ffixed-line-length-none -ffree-line-length-none -finit-local-zero -Ofast -mtune=native -march=native -ffast-math -mfpmath=sse -msse2 -ffast-math -g -fPIC"
          cd ../response
          f2py3 -c -m f90response response.F90 --f90flags="-m64 -cpp -ffixed-line-length-none -ffree-line-length-none -finit-local-zero -Ofast -mtune=native -march=native -ffast-math -mfpmath=sse -msse2 -ffast-math -g -fPIC"
      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=app test/ > pytest-coverage.txt
      - name: Pytest Coverage Commentator (More Expressive with 'with:')
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
